blog/urls.py
from django.urls import path
from .views import detail_article, home ,category 




app_name = "blog"

urlpatterns = [
    path ('', home , name='home'),
    path ('page/<int:page>', home , name='home'),
    path ('article/<slug:slug>' ,detail_article , name ='detail_article'),
    path ('category/<slug:slug>' ,category , name='category'),
    path ('category/<slug:slug>/page/<int:page>', category , name='category'),

]

webloot/urls.py
from django.contrib import admin
from django.urls import path ,include
# django static files in debug mode
from django.conf import settings
from django.conf.urls.static import static
# ---------------------

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from django.db.models.expressions import OrderBy
from django.db.models.fields.related import create_many_to_many_intermediary_model
from django.utils import timezone
from extensions.utils import jalali_converter
# Create your models here.

# managers in django ,(object is a manager for example)
# my manager
class ArtilceManager(models.Manager):
    def published(self):
        return self.filter(status = 'p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status = True)


class Category(models.Model):
    parent = models.ForeignKey('self', null=True , blank=True ,on_delete=models.SET_NULL,related_name='children',verbose_name='زیر دسته' )
    title = models.CharField(max_length=200 , verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=100 ,unique=True ,verbose_name='اسلاگ دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا دسته نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسنه بندی ها'
        ordering =['parent__id' , 'position'] 
    def __str__(self):
        return self.title

    # manager for category
    objects = CategoryManager()

class Article(models.Model):
    STATUS_CHOICES =(
        # ('d','Draft'),
        # ('p','Published'),
        ('d','پیش نویس'),
        ('p','منتشر شده'),
    )
    title = models.CharField(max_length=255 , verbose_name='عنوان')
    slug = models.SlugField(max_length=100 , unique=True,verbose_name='اسلاگ')
    category = models.ManyToManyField(Category,verbose_name='دسته بندی', related_name='articles')
    descriptions = models.TextField(verbose_name='توضیحات')
    thumbnail = models.ImageField(upload_to='images' ,blank = True, null=True , verbose_name='تصویر')
    publish = models.DateTimeField(default=timezone.now , verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True , verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True , verbose_name='زمان آپدیت')
    status = models.CharField(max_length=1 , choices=STATUS_CHOICES ,verbose_name='وضعیت')

    # farsi sazi
    class Meta :
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering=['-publish']


    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'زمان انتشار'

    # method for just show published category , and we used in template to doesnot show no published cats
    def category_published(self):
        return self.category.filter(status = True)
    
    # and continue of my manager
    objects = ArtilceManager()

  

blog/views.py
# paginator
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
# from django.http import HttpResponse , JsonResponse
from .models import Article, Category 


# Create your views here.

def home(request , page=1 ):
    articles_list = Article.objects.published()
    paginator = Paginator(articles_list , 4)
    # page = request.GET.get('page')
    articles = paginator.get_page(page)

    # context={
    #     'name': 'arash',
    #     'age': 25,
    #     'job':'programmer' 
    # }
    # # context ={
    #     'articles':
    #     [
    #         {
    #             'title': 'برد ۶ گله حریف آسیایی پرسپولیس',
    #             'descriptions':'به گزارش "ورزش سه"، در یکی از مسابقات هفته پانزدهم ویسشایا لیگا تاجیکستان، تیم فوتبال استقلال دوشنبه که حریف پرسپولیس ایران در لیگ قهرمانان آسیا است، از ساعت ۲۰ یکشنبه شب مقابل تیم رده ششمی خالتون قرار گرفت.',
    #             'img':'https://static.farakav.com/files/pictures/thumb/01602762.jpg'
    #         },
    #         {
    #             'title': 'حمایت از لیونل مسی روی سکوهای نوکمپ (عکس)',
    #             'descriptions':'به گزارش "ورزش سه"، 20348 هوادار حاضر در نوکمپ پیش از بازی بارسا برابر سوسیداد و نیز در جریان بازی با سر دادن شعارهایی به حمایت از لیونل مسی اسطوره خود پرداختند.',
    #             'img':'https://static2.farakav.com/files/pictures/01634654.jpg'
    #         },
    #         {
    #             'title': 'شگفت‌انگیز است؛ از پیوستن‌ به قهرمان‌ایتالیا خوشحالم',
    #             'descriptions':'استفان دی فرای دوست من است و ما از یک شهر هستیم. من او را خیلی خوب می شناسم و خوشحالم که اینجاست و با یکدیگر هم تیمی هستیم. ',
    #             'img':'https://static2.farakav.com/files/pictures/01634457.jpg'
    #         },
    #     ]
    # }

    context ={
        # use manager instead of status = ...
        # 'articles':Article.objects.filter(status = 'p') ,
        # 'articles':Article.objects.published(),
        'articles':articles,

        # category added for show in home page
        # 'category':Category.objects.filter(status=True)
    }
    return render(request , "blog/home.html" , context ) 

def detail_article(request , slug ):
    context = {
        # 'article':Article.objects.get(slug = slug)
        # use manager instead of status = ...
        # 'article':get_object_or_404(Article , slug = slug , status = 'p'),

        'article':get_object_or_404(Article.objects.published() , slug = slug ),

        # 'category':Category.objects.filter(status=True)
    }
    return render (request , 'blog/detail_article.html' , context)


def category(request,slug ,page =1):
    category = get_object_or_404(Category , slug = slug , status =True)
    articles_list = category.articles.published()
    paginator = Paginator(articles_list , 4)
    articles = paginator.get_page(page)

    context = {

        'category': category,
        'articles':articles

    }
    return render (request , 'blog/category.html' , context)







# def home(request):
#     return HttpResponse ('welcome to webloot')
# ------------------------------------------------------------------
# def api(request):
#     return JsonResponse ({'title':'سلام'}

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en ">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Persian Merchant Trade Map{% block title %}{% endblock  %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <!-- arash : rtl.css added -->
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- <a class="navbar-brand" href="/">{% title %}</a> -->
                <a class="navbar-brand" href="/"></a>
                    <!-- <img src="{% static 'blog/assets/img/bloot.jpg' %}" alt="webloot logo" style="width:100px;">  -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
               <!-- inclusion tags in base_tags.py -->
                {% category_navbar %}

            </div>
        </nav>
       
        <!-- Main Content-->
        
        {% block main %}{% endblock  %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a target='_blank' href="https://t.me/pmtmap">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-telegram fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a target='_blank' href="https://wa.me/+989981339245">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-whatsapp fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item" >
                                <a target='_blank' href="https://www.instagram.com/pmtmap/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                           
                            <li class="list-inline-item">
                                <a href="tel:{{ +989039566483 }}" title="Phone">
                                  <span class="fa-stack fa-lg" aria-hidden="true">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fas fa-phone fa-stack-1x fa-inverse"></i>
                                  </span>
                                  <span class="sr-only">+989039566483</span>
                               </a>
                            </li>
                            <li class="list-inline-item">
                                <a target='_blank' href="https://github.com/webaloot-team/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div style="text-align: center !important;" >
                            <img src="{% static 'blog/assets/img/info.png' %}" alt="Qecode" style="width:100px;">
                        </div>
                       
                        
                        <br/>
                        <div class="small text-center text-muted fst-italic">  
                            <svg style="text-align: center !important;"  xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
                                    
                                </svg>  <a href="mailto:info@pmtmap.com">info@pmtmap.com</a>
                        </div>

                        <div class="small text-center text-muted fst-italic">Copyright &copy; arashzare.ir  2022</div>
                        

                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block main %}
{% load static %}
  <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>PmtMap</h1>
                            <span class="subheading">Persian Merchant Trade Map</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            <h3 class="alert alert-secondary text-center"> Category: {{category.title}}</h3>
            <!-- articles is telated_name in model category manytomany -->
            <!-- here we should user manager in django for filter published ..>
                   
            my manger in models.py -->

        {% comment %} {% for article in category.article.all %} {% endcomment %}
            {% for article in articles %}

              <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail_article' article.slug %}">
                    <h2 class="post-title">{{article.title}}</h2>
                    <h4 class="post-subtitle">{{article.descriptions | truncatewords:30 | safe}}</h4>
                </a>
                <p class="post-meta">
                    نوشته شده توسط 
                    <a href="#">حسین محمودی</a>
                    {{article.jpublish}}
                </p>
                <div>
                 <!-- models.py category_published -->
                    {% for cat in article.category_published.all %}
                    <a href="{% url 'blog:category' cat.slug %}"> # {{cat.title}}</a>
                    
                    {% endfor %}
                </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->

        {% endfor %}
           
           
            <!-- Pager-->
            <!-- Pager-->
            <div class="d-flex justify-content-between mb-4">
                {% if articles.has_previous %}
            <a class="btn btn-primary  text-uppercase " href="{% url 'blog:category' category.slug articles.previous_page_number%}"> &rarr; پست های جدید </a>
                {% endif %}
                {% if articles.has_next %}
            <a class="btn btn-primary text-uppercase d" href="{% url 'blog:category' category.slug articles.next_page_number%}">  پست های قدیمی &larr;</a>
                {% endif %}            
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/detail_article.html
{% extends 'blog/base.html' %}
{% block title %}  | {{article.title}} {% endblock  %}
{% block main %}

  <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{article.title}}</h1>
                            <span class="subheading">Persian Merchant Trade Map</span>
                                <small>{{article.jpublish}}</small>

                        </div>
                    </div>
                </div>
            </div>
        </header>


<article class="mb-4 text-justify">
            <div class="container px-4 px-lg-5 ">
                <div class="row gx-4 gx-lg-8 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-10 ">
                        <!-- <p>{{post.body | safe}}</p> -->
                        {{article.descriptions | safe }}
                    </div>
                </div>
            </div>
</article>

{% endblock  %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block main %}
{% load static %}
  <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'blog/assets/img/about-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>PmtMap</h1>
                            <!-- <span class="subheading">طراحی وب سایت حرفه ای</span> -->
                            <span class="subheading">welcome to Persian Merchant Trade Map </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
        {% for article in articles %}
              <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail_article' article.slug %}">
                    <h3 class="post-title">{{article.title}}</h3>
                    <h5 class="post-subtitle">{{article.descriptions | truncatewords:30 | safe}}</h5>
                </a>
                <br/>
                <p class="post-meta">
                    نوشته شده توسط 
                    <!-- Written by -->
                    <a href="#"> حسین محمودی</a>
                    {{article.jpublish}}
                </p>
                <div>
                <!-- models.py category_published  and in category.html too-->
                    {% comment %} {% for cat in article.category.all %} {% endcomment %}
                    {% for cat in article.category_published.all %}

                    <a href="{% url 'blog:category' cat.slug %}"> # {{cat.title}}</a>
                    
                    {% endfor %}
                </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->

        {% endfor %}
           
           
            <!-- Pager-->
            <div class="d-flex justify-content-between mb-4">
                {% if articles.has_previous %}
            <!-- <a class="btn btn-primary  text-uppercase " href="{% url 'blog:home' articles.previous_page_number%}"> &rarr; پست های جدید </a> -->
            <a class="btn btn-primary  text-uppercase " href="{% url 'blog:home' articles.previous_page_number%}"> &rarr; New Posts </a>
                {% endif %}
                {% if articles.has_next %}
            <a class="btn btn-primary text-uppercase d" href="{% url 'blog:home' articles.next_page_number%}">  Older Posts &larr;</a>
                {% endif %}            
            </div>

        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/partials/category_loop_child.html
<ul class="navbar-nav ml-auto">
    {% for cat in cat.children.all %}
        <li class="nav-item ">
            <a class="nav-link " href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                
                   <!-- use categorymanager for filter  -->
                    {% comment %} {% if cat.children.all %} {% endcomment %}
                    {% if cat.children.active %}
                    
                    {% include 'blog/partials/category_loop_child.html' %}
                {%endif%}
        </li>
                    
    {% endfor %}
</ul>

blog/templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse nav " id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
        </li>
    
        {% for cat in category %}
            {% if cat.parent == None %}
                <li class="nav-item ">
                    <a class="nav-link " href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                        <!-- use categorymanager for filter  -->
                    {% comment %} {% if cat.children.all %} {% endcomment %}
                    {% if cat.children.active %}
                        {% include 'blog/partials/category_loop_child.html' %}
                    {%endif%}
                </li>
            {% endif %}
        {% endfor%}
    </ul>

</div>